Coroutines/RxJava
almoiv0499/NewsNow pull request #11
Opened 2022-07-20 16:00 UTC by almoiv0499

2022-07-21 09:31 UTC, AlexeyGvozdev requested changes

2022-07-21 09:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +            if (response.isSuccessful) {
а если будет ошибка, то что будет?

2022-07-21 09:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +            generateCall(view)
назови лучше fetchAllNews

2022-07-21 09:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +            val response = RetrofitInstance.getInstance().api.getAllNews(Category.ARTS.category).awaitResponse()
awaitResponse не обязательно нужен. Ты можешь в функции getAllNews изменить возвращаемое значение с Call<Result> на Result

2022-07-21 09:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +    private suspend fun generateCall(view: View) {
давай этот вариант оставим

2022-07-21 16:21 UTC, almoiv0499 commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +            val response = RetrofitInstance.getInstance().api.getAllNews(Category.ARTS.category).awaitResponse()
Если сделать вместо Result, чтобы getAllNews() возвращал Response<ListNews>, где далее я буду делать проверку, если ответ успешен, то добавляю данные в addPosters(), можно так?

2022-07-24 15:41 UTC, AlexeyGvozdev requested changes

2022-07-24 15:41 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +    private suspend fun getNews() = withContext(Dispatchers.IO) {
лишняя функция

2022-07-24 15:41 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +        val results = getNews()
а что будет если при вызове сетевого запроса будет ошибка (Exception)?

2022-07-24 18:10 UTC, almoiv0499 commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +        val results = getNews()
Так как вызов у меня происходит в дочерней корутине, и если она поймает Exception, то она его потянет вверх до родительской и, если нигде не обрабатывается, то приложение крашнется. Я предполагаю, что можно при помощи exception handler'а обработать данное исключение, добавив его параметром в родительскую корутину

2022-07-25 19:06 UTC, AlexeyGvozdev requested changes

2022-07-25 19:06 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +                throw HttpException(exception.response())
Шило на мыло поменял. У тебя же приложение упадёт при ошибке, а надо показать пользователю, что произошла ошибка

2022-07-25 19:06 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/TopNewsFragment.kt
> +                return@withContext RetrofitInstance.getInstance().api.getNewsForTopNewsScreen()
Это что такое? try в котлине возвращает значение return не нужен

2022-08-02 17:45 UTC, merged