Changed Design
almoiv0499/NewsNow pull request #7
Opened 2022-06-05 16:48 UTC by almoiv0499

2022-06-05 17:31 UTC, AlexeyGvozdev requested changes

2022-06-05 17:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/adapter/NewsAdapter.java
> +    @RequiresApi(api = Build.VERSION_CODES.O)
Что это значит?

2022-06-05 17:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/NewsDetailFragment.java
> +        return author.split(NewsViewHolder.SPLIT_WORD)[NewsViewHolder.INDEX_ZERO];
Как-то странно, что фрагмент знает про константы вьюхолдера

2022-06-05 17:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/model/ListNews.java
> +    @SerializedName("results")
ты мог просто в аннотации поменять, и не надо было бы название поля менять

2022-06-05 17:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/viewholder/NewsViewHolder.java
> +    private Multimedia multimedia;
зачем что-то сохранять во вьюхолдере?

2022-06-05 17:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/viewholder/NewsViewHolder.java
> +    private String convertDateTime(String date) {
какие-то вычисления не надо делать в адаптере. Только отрисовка

2022-06-05 17:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/viewholder/NewsViewHolder.java
> +    private String convertDateTime(String date) {
и ты просто продублировал функцию из фрагмента?

2022-06-05 17:31 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/viewholder/NewsViewHolder.java
> +    private String convertDateTime(String date) {
в адаптер передаём уже конечные данные, которые просто надо отрисовать

2022-06-05 17:31 UTC, AlexeyGvozdev commented on app/src/main/res/layout/recycler_top_news_layout.xml
> +    android:layout_height="350dp"
а что если на планшете открыть? Или повернуть телефон?

2022-06-05 18:50 UTC, almoiv0499 commented on app/src/main/java/com/application/newsnow/model/ListNews.java
> +    @SerializedName("results")
Да, я знаю
Поменял, чтобы в дальнейшем путаницы не было

2022-06-05 18:54 UTC, almoiv0499 commented on app/src/main/java/com/application/newsnow/viewholder/NewsViewHolder.java
> +    private Multimedia multimedia;
Это исправил

2022-06-05 18:56 UTC, almoiv0499 commented on app/src/main/res/layout/recycler_top_news_layout.xml
> +    android:layout_height="350dp"
Вернул значение на 400, тк при повороте при 350sp обрезало, сейчас не так сильно

2022-06-05 19:01 UTC, almoiv0499 commented on app/src/main/java/com/application/newsnow/adapter/NewsAdapter.java
> +    @RequiresApi(api = Build.VERSION_CODES.O)
При `OffsetDateTime.parse()` этом методе студия указывает, чтобы я установил данную аннотацию
Она означает, что данный метод стоит вызывать только у устройств с API 26 и выше

2022-06-06 19:43 UTC, AlexeyGvozdev requested changes

2022-06-06 19:43 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/fragment/NewsDetailFragment.java
> +    @RequiresApi(api = Build.VERSION_CODES.O)
Это не убрал?

2022-06-06 19:43 UTC, AlexeyGvozdev commented on app/src/main/java/com/application/newsnow/model/News.java
> +
пустая строка

2022-06-06 20:59 UTC, merged